// Generated by CoffeeScript 1.6.3
/*
@desc Implements the move functionality. Images can be moved by clicking and dragging on it.
@author Michael Kaserer e1025263@student.tuwien.ac.at
@required All tools must implement following functions:
click(x, y, painters)
mousedown(x, y, painters)
mouseup(x, y, painters)
mousemove(x, y, painters)
mouseout(x, y, painters)
*/


(function() {
  this.Move = (function() {
    function Move() {
      this.started = false;
      this.curX = 0;
      this.curY = 0;
    }

    Move.prototype.click = function() {};

    Move.prototype.mousedown = function() {
      return this.started = true;
    };

    Move.prototype.mouseup = function() {
      return this.started = false;
    };

    Move.prototype.mousemove = function(x, y, painters) {
      var deltaX, deltaY, newPanX, newPanY, painter, _i, _len;
      if (this.started) {
        deltaX = x - this.curX;
        deltaY = y - this.curY;
        newPanX = painters[0].getPan()[0] + deltaX;
        newPanY = painters[0].getPan()[1] + deltaY;
        for (_i = 0, _len = painters.length; _i < _len; _i++) {
          painter = painters[_i];
          painter.setPan(newPanX, newPanY);
          painter.drawImg();
        }
      }
      this.curX = x;
      return this.curY = y;
    };

    Move.prototype.mouseout = function() {
      return this.started = false;
    };

    return Move;

  })();

}).call(this);
