// Generated by CoffeeScript 1.6.3
/*
@desc This JavaScript worker takes the number of files and perform
progress with a certain delay for the progressbar.
It posts the current percentual value of the progressbar back to the HTML file.
@author Michael Kaserer e1025263@student.tuwien.ac.at
*/


(function() {
  var current, max, progress,
    _this = this;

  current = 0;

  max = 100;

  this.addEventListener('message', function(e) {
    max = e.data;
    return _this.postMessage("Max: " + max);
  }, false);

  progress = setInterval(function() {
    _this.postMessage("Max: " + max);
    if (current >= max) {
      return clearInterval(progress);
    } else {
      current += 5;
      return _this.postMessage(((current / max) * 100).toFixed(0));
    }
  }, 20);

}).call(this);
