// Generated by CoffeeScript 1.6.3
/*
@desc Implements the windowing function functionality.
@author Michael Kaserer e1025263@student.tuwien.ac.at
@required All tools must implement following functions:
click(x, y, painters)
mousedown(x, y, painters)
mouseup(x, y, painters)
mousemove(x, y, painters)
mouseout(x, y, painters)
*/


(function() {
  this.WindowLevel = (function() {
    var click;

    function WindowLevel() {
      this.started = false;
      this.curX = 0;
      this.curY = 0;
    }

    click = function() {};

    WindowLevel.prototype.mousedown = function() {
      return this.started = true;
    };

    WindowLevel.prototype.mouseup = function() {
      return this.started = false;
    };

    WindowLevel.prototype.mousemove = function(x, y, painters) {
      var curWindowing, deltaX, deltaY, newX, newY, painter, _i, _len;
      if (this.started) {
        curWindowing = painters[0].getWindowing();
        deltaX = x - this.curX;
        deltaY = this.curY - y;
        newX = curWindowing[0] + deltaX;
        newY = curWindowing[1] + deltaY;
        for (_i = 0, _len = painters.length; _i < _len; _i++) {
          painter = painters[_i];
          painter.setWindowing(newX, newY);
          painter.drawImg();
        }
        $('.wCenter').text("WC: " + (newX.toFixed(0)));
        $('.wWidth').text("WW: " + (newY.toFixed(0)));
      }
      this.curX = x;
      return this.curY = y;
    };

    WindowLevel.prototype.mouseout = function() {
      return this.started = false;
    };

    return WindowLevel;

  })();

}).call(this);
