// Generated by CoffeeScript 1.6.3
/*
@desc Implements the zoom functionality.
@author Michael Kaserer e1025263@student.tuwien.ac.at
@required All tools must implement following functions:
click(x, y, painters)
mousedown(x, y, painters)
mouseup(x, y, painters)
mousemove(x, y, painters)
mouseout(x, y, painters)
*/


(function() {
  this.Zoom = (function() {
    function Zoom() {
      this.started = false;
      this.curY = 0;
    }

    Zoom.prototype.click = function() {};

    Zoom.prototype.mousedown = function() {
      return this.started = true;
    };

    Zoom.prototype.mouseup = function() {
      return this.started = false;
    };

    Zoom.prototype.mousemove = function(x, y, painters) {
      var deltaY, newDeltaY, painter, _i, _len;
      if (this.started) {
        deltaY = this.curY - y;
        newDeltaY = painters[0].getScale() + deltaY / 100.0;
        for (_i = 0, _len = painters.length; _i < _len; _i++) {
          painter = painters[_i];
          painter.setScale(newDeltaY);
          painter.drawImg();
        }
      }
      return this.curY = y;
    };

    Zoom.prototype.mouseout = function() {
      return this.started = false;
    };

    return Zoom;

  })();

}).call(this);
